# Yaml model for Penguin Clash Game

settings:

  world:
    # 736
    max_x: 74
    # 414
    max_y: 42

  island:
    # 368
    center_x: 37
    # 207
    center_y: 21
    # 162.5
    small_radius: 17
    # 251.5
    big_radius: 26

  penguin:
    # 27
    radius: 3
    # 5.4
    move_velocity: 1
    # 10
    flash_velocity: 2
    # 10
    snowball_ox: 1
    # 15
    snowball_oy: 2
    # 3.0
    sliding_friction: 3

  snowball:
    # 10
    radius: 1
    # 1.2
    fly_velocity: 1

  insertions:
    # required 300
    init_x1: 30
    # required 207
    init_y1: 21
    # required 0
    init_direction1: 0
    # required 300
    init_x2: 37
    # required 207
    init_y2: 21
    # required 0
    init_direction2: 180